version: '3.9'

services:
  db: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 3000:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    ports:
      - 8888:8888
    env_file:
      - .env
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
